# Generated by Django 5.2 on 2025-08-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname',
            field=models.CharField(default='New name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='history',
            field=models.TextField(default='history', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='jpname',
            field=models.CharField(default='ja name', max_length=100),
            preserve_default=False,
        ),
    ]
