# Generated by Django 5.2 on 2025-08-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='image',
            field=models.ImageField(unique=True, upload_to='thankjapan/images/'),
        ),
    ]
