# Generated by Django 5.2 on 2025-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname',
            field=models.CharField(default='new data', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='history',
            field=models.TextField(default='new history', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='jpname',
            field=models.CharField(default='new name', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
