# Generated by Django 5.2 on 2025-08-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0002_thankjapanmodel_englishname_thankjapanmodel_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='englishname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='jpname',
            field=models.CharField(max_length=100),
        ),
    ]
