# Generated by Django 5.2 on 2025-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0002_alter_thankjapanmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='image',
            field=models.ImageField(upload_to='thankjapan/images/'),
        ),
    ]
