# Generated by Django 5.2 on 2025-10-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0002_thankjapanmodel_englishname_thankjapanmodel_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('last_score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
