# Generated by Django 5.2 on 2025-08-07 05:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0003_alter_thankjapanmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
