# Generated by Django 5.2 on 2025-10-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='toru0514', max_length=128),
            preserve_default=False,
        ),
    ]
