# Generated by Django 5.2 on 2025-10-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0004_player_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
