# Generated by Django 5.2 on 2025-08-07 06:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0004_alter_thankjapanmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanmodel',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image'),
        ),
    ]
