# Generated by Django 5.2 on 2025-08-08 04:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0005_thankjapanmodel_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThankJapanBackgroundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image')),
            ],
        ),
        migrations.CreateModel(
            name='ThankJapanImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
