# Generated by Django 5.2 on 2025-10-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0005_thankjapanmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
