# Generated by Django 5.2 on 2025-12-29 04:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThankJapanPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('englishname', models.CharField(max_length=200)),
                ('jpname', models.CharField(max_length=200)),
                ('romaji', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('category', models.CharField(max_length=100)),
                ('jlpt_level', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('history', models.TextField(max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
