# Generated by Django 5.2 on 2026-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0008_thankjapanpremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_policy_version',
            field=models.CharField(default='2025-08', max_length=10),
        ),
    ]
