# Generated by Django 5.2 on 2026-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0010_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
