# Generated by Django 5.2 on 2026-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0011_profile_paypal_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_bonus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
