# Generated by Django 5.2 on 2026-02-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0012_profile_last_bonus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanmodel',
            name='kanji_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='katakana_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
