# Generated by Django 5.2 on 2026-02-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0013_thankjapanmodel_kanji_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanpremium',
            name='kanji_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='katakana_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
