# Generated by Django 5.2 on 2026-02-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0014_thankjapanpremium_kanji_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='privacy_policy_version',
            field=models.CharField(default='2026-2', max_length=10),
        ),
    ]
