# Generated by Django 5.2 on 2026-02-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0017_alter_thankjapanmodel_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_de',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_en_in',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_es_es',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_es_mx',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_fr',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_it',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_ja',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_ko',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_pt',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_pt_br',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_th',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_vi',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_zh_cn',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='description_zh_hant',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_de',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_en_in',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_es_es',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_es_mx',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_fr',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_it',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_ja',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_ko',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_pt',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_pt_br',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_th',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_vi',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_zh_cn',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='history_zh_hant',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
