# Generated by Django 5.2 on 2026-02-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0018_thankjapanpremium_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_de',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_en_in',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_es_es',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_es_mx',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_fr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_it',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_ja',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_ko',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_pt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_pt_br',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_th',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_vi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_zh_cn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='englishname_zh_hant',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_de',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_en_in',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_es_es',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_es_mx',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_it',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_ja',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_ko',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_pt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_pt_br',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_th',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_vi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_zh_cn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='englishname_zh_hant',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
