# Generated by Django 5.2 on 2026-04-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0020_weeklyscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyscore',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
