# Generated by Django 5.2 on 2026-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0021_weeklyscore_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_en_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_es_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_es_mx',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_it',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_pt_br',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_romaji',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_vi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_zh_cn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanmodel',
            name='example_sentence_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
    ]
