# Generated by Django 5.2 on 2026-05-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0022_thankjapanmodel_example_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_de',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_en_in',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_es_es',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_es_mx',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_fr',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_it',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_ja',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_ko',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_pt',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_pt_br',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_romaji',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_th',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_vi',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_zh_cn',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanpremium',
            name='example_sentence_zh_hant',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
