# Generated by Django 5.2 on 2026-07-23 20:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0023_thankjapanpremium_example_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankjapanbackgroundmodel',
            name='page_type',
            field=models.CharField(blank=True, choices=[('top', 'トップ画面'), ('quiz_menu', 'クイズ選択画面'), ('game', 'ゲーム画面'), ('result', '結果画面'), ('study', '学習詳細画面'), ('region', '地域探索画面')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thankjapanbackgroundmodel',
            name='sound',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sound'),
        ),
    ]
