# Generated by Django 5.2 on 2026-07-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0024_thankjapanbackgroundmodel_page_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanbackgroundmodel',
            name='page_type',
            field=models.CharField(blank=True, choices=[('top', 'トップ画面'), ('quiz_menu', 'クイズ選択画面'), ('game', 'ゲーム画面'), ('result', '結果画面'), ('study_select', '学習選択画面'), ('study', '学習詳細画面'), ('region', '地域探索画面')], max_length=20, null=True),
        ),
    ]
