# Generated by Django 5.2 on 2026-08-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0027_profile_streak_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='review_prompt_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='review_prompt_dismissed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='viewed_word_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
