# Generated by Django 5.2 on 2026-08-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0028_profile_review_prompt_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_reminder_step_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
