# Generated by Django 5.2 on 2026-08-26 05:52

from django.db import migrations

# Must match the highest day-tier in thank_japan_app/management/commands/send_reminders.py.
MAX_REMINDER_STEP = 30


def grandfather_existing_profiles(apps, schema_editor):
    """
    send_reminders.py used to match on last_bonus_date == exact target date. This
    release switches it to a >= N days idle range, tracked via last_reminder_step_sent
    so each tier only fires once. Without this backfill, every profile that is
    already >=2/7/30 days idle at deploy time would match all applicable tiers on
    the very next run and get a burst of catch-up notifications all at once.

    So: mark every profile that existed before this migration as having already
    "received" every tier, up to the highest one. This only affects the backlog —
    it does not touch new idle periods that start after this deploy, since
    last_reminder_step_sent is reset to 0 whenever the user is active again
    (see apply_login_bonus in views.py).
    """
    Profile = apps.get_model('thank_japan_app', 'Profile')
    Profile.objects.update(last_reminder_step_sent=MAX_REMINDER_STEP)


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0029_profile_last_reminder_step_sent'),
    ]

    operations = [
        migrations.RunPython(grandfather_existing_profiles, migrations.RunPython.noop),
    ]
