# Generated by Django 5.2 on 2026-08-27 05:48

import thank_japan_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0030_grandfather_reminder_step_for_existing_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanbackgroundmodel',
            name='background_image',
            field=thank_japan_app.fields.OptimizedCloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='image',
            field=thank_japan_app.fields.OptimizedCloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='thankjapanpremium',
            name='image',
            field=thank_japan_app.fields.OptimizedCloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
