# Generated by Django 5.2 on 2026-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0032_profile_best_combo_profile_games_played_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_play_purchase_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
