# Generated by Django 5.2 on 2026-09-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0034_dailyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_question_notify',
            field=models.BooleanField(default=False),
        ),
    ]
