# Generated by Django 5.2 on 2026-09-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0035_profile_daily_question_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trial_ended_popup_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
