# Generated by Django 5.2 on 2026-09-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0036_profile_trial_ended_popup_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='review_prompt_shown',
            field=models.BooleanField(default=False),
        ),
    ]
