# Generated by Django 5.2 on 2025-05-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThankJapanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=1000)),
                ('image', models.ImageField(height_field=500, upload_to='', width_field=900)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
