# Generated by Django 5.2 on 2025-05-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0002_alter_thankjapanmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thankjapanmodel',
            old_name='discription',
            new_name='description',
        ),
    ]
