# Generated by Django 5.2 on 2025-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0003_rename_discription_thankjapanmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
