# Generated by Django 5.2 on 2025-05-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thank_japan_app', '0004_alter_thankjapanmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thankjapanmodel',
            name='image',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
